### ISSUE TITLE
File selected at start up is not highlighted until you do an action in the vault exlporer

### ISSUE THREAD

**Issue by erasels** [justanotherjurastudent/highlight-active-folder-section#5]
When I reopen Obsidian, it restores my tabs and puts me on my last visited file. At this point, the highlighting is not active. Only when I click on it or somehow navigate to a new file does it update the highlighting.

**Comment by justanotherjurastudent** [comment]
Hi @erasels, unfortunately, I can't reproduce this issue. I'm aware that the issue was present in the initial version of this plugin, but I have since implemented a rule that the highlights should activate themselves in less than a second. I closed my Obsidian and reopened it, and it worked as expected. As you mentioned, the highlights do appear, even when they don't work automatically, by clicking on a note.

**Comment by erasels** [comment]
It must be an incompatibility with one of my many plug-ins then. I tried disabling those that do something obvious on start-up like Git integration, Custom Folder Sorting and Hide Folders, but that didn't fix it either. 
Oh well, thanks for taking the time to check on your end.

**Comment by justanotherjurastudent** [comment]
@erasels You are welcome!
